# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.10"
  - "3.9"
  - "3.8"
  - "3.7"

env:
  - DJANGO_VERSION=django-31
  - DJANGO_VERSION=django-32
  - DJANGO_VERSION=django-40

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e "$(echo py$TRAVIS_PYTHON_VERSION | tr -d .)-$DJANGO_VERSION"

after_success:
  - codecov -e "$(echo py$TRAVIS_PYTHON_VERSION | tr -d .)-$DJANGO_VERSION"
